require('dotenv').config();
const express = require('express');
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const QRCode = require('qrcode');
const crypto = require('crypto');
const { Pool } = require('pg');

const app = express();
const PORT = Number(process.env.PORT || 8080);
const ROOT = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const JWT_SECRET = process.env.JWT_SECRET || (process.env.NODE_ENV === 'production' ? '' : 'dev-only-spiro-karen-secret');
if (process.env.NODE_ENV === 'production' && JWT_SECRET.length < 32) throw new Error('JWT_SECRET must be at least 32 characters in production');
const DATA = path.join(ROOT, 'data.json');
const useDb = !!process.env.DATABASE_URL;
const pool = useDb ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized:false } : undefined }) : null;
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(self), microphone=(), geolocation=()');next()});
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin', process.env.CORS_ORIGIN || '*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});

const seed={users:[{id:'USR-001',name:'System Admin',email:'admin@spirokaren.local',role:'ADMIN',passwordHash:bcrypt.hashSync('Admin123!',10)}],customers:[],products:[{id:'P-001',sku:'SWAP-001',name:'Battery Swap',category:'Battery Swap',price:150,stock:999999,reorder:0,active:true},{id:'P-002',sku:'TRAIN-001',name:'Rider Safety Training',category:'Training',price:1000,stock:100,reorder:10,active:true},{id:'P-003',sku:'HELM-001',name:'Safety Helmet',category:'Equipment',price:1800,stock:50,reorder:10,active:true}],tickets:[],sales:[],swaps:[],stations:[],batteries:[],drivers:[],payments:[],shifts:[],expenses:[],audit:[]};
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{fs.writeFileSync(DATA,JSON.stringify(seed,null,2));return structuredClone(seed)}}
function save(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired token'})}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Insufficient permissions'})}
async function audit(action,entity,entityId,user,meta={}){const id=`AUD-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`;if(useDb){await q('insert into audit(id,action,entity,entity_id,user_email,meta) values($1,$2,$3,$4,$5,$6)',[id,action,entity,entityId,user?.email||'system',JSON.stringify(meta)]);return}const d=load();d.audit.unshift({id,action,entity,entityId,user:user?.email||'system',meta,createdAt:new Date().toISOString()});d.audit=d.audit.slice(0,5000);save(d)}
function ticketId(){const d=new Date();const day=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;const n=String(load().tickets.length+1).padStart(4,'0');return `SK-${day}-${n}`}
function saleId(){return `SALE-${new Date().getFullYear()}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`}
function expiryStatus(t){if(t.status==='ACTIVE'&&t.expiry&&new Date(t.expiry)<new Date())return 'EXPIRED';return t.status}
async function q(text,params=[]){return pool.query(text,params)}
async function ensureDb(){
 if(!useDb)return;
 const schema=fs.readFileSync(path.join(ROOT,'schema.sql'),'utf8'); await q(schema);
 const u=await q('select count(*)::int n from users'); if(!u.rows[0].n){const s=seed.users[0];await q('insert into users(id,name,email,role,password_hash) values($1,$2,$3,$4,$5)',[s.id,s.name,s.email,s.role,s.passwordHash])}
}

app.get('/api/health',async(req,res)=>{let db='demo-json';try{if(useDb){await q('select 1');db='postgresql'}}catch(e){return res.status(503).json({ok:false,service:'Spiro Karen Business System API',mode:'postgresql',database:'unavailable',error:'Database unavailable',time:new Date().toISOString(),version:'3.0.0'})}res.json({ok:true,service:'Spiro Karen Business System API',mode:db,database:db==='postgresql'?'ready':'not configured',time:new Date().toISOString(),version:'3.0.0'})});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body||{};let u;if(useDb){const r=await q('select id,name,email,role,password_hash from users where lower(email)=lower($1)',[email]);u=r.rows[0]}else u=load().users.find(x=>x.email.toLowerCase()===String(email||'').toLowerCase());if(!u||!bcrypt.compareSync(password||'',u.password_hash||u.passwordHash))return res.status(401).json({error:'Invalid credentials'});const user={id:u.id,name:u.name,email:u.email,role:u.role};audit('LOGIN','USER',u.id,user);res.json({token:jwt.sign(user,JWT_SECRET,{expiresIn:'12h'}),user})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/me',auth,(req,res)=>res.json(req.user));

// Dashboard / business intelligence
app.get('/api/dashboard',auth,async(req,res)=>{try{if(useDb){const [s,p,t,b,d,e]=await Promise.all([q("select count(*)::int n,coalesce(sum(amount),0) revenue from sales where created_at::date=current_date and status='PAID'"),q("select count(*)::int n from payments where created_at::date=current_date and status='Success'"),q("select count(*)::int n from tickets where issued_at::date=current_date"),q("select count(*)::int n from batteries where status='Available'"),q("select count(*)::int n from drivers where status='Active'"),q("select coalesce(sum(amount),0) total from expenses where spent_at::date=current_date")]);return res.json({sales:s.rows[0],payments:p.rows[0],tickets:t.rows[0],availableBatteries:b.rows[0].n,activeDrivers:d.rows[0].n,expenses:e.rows[0].total})}const d=load(),today=new Date().toISOString().slice(0,10),sales=d.sales.filter(x=>String(x.createdAt||'').slice(0,10)===today&&x.status==='Paid');res.json({sales:{n:sales.length,revenue:sales.reduce((a,x)=>a+Number(x.amount||0),0)},payments:{n:d.payments.filter(x=>x.status==='Success').length},tickets:{n:d.tickets.filter(x=>String(x.issued||x.issuedAt||'').includes(today)).length},availableBatteries:d.batteries.filter(x=>x.status==='Available').length,activeDrivers:d.drivers.filter(x=>x.status==='Active').length,expenses:d.expenses.reduce((a,x)=>a+Number(x.amount||0),0)})}catch(e){res.status(500).json({error:e.message})}});

// Generic resource helpers
function memoryList(resource){return load()[resource]||[]}
for(const resource of ['stations','batteries','drivers','customers','products','shifts','expenses','audit']){
 app.get(`/api/${resource}`,auth,async(req,res)=>{try{if(useDb){const r=await q(`select * from ${resource} order by 1 desc`);return res.json(r.rows)}res.json(memoryList(resource))}catch(e){res.status(500).json({error:e.message})}})
}
app.post('/api/products',auth,role('ADMIN','MANAGER'),async(req,res)=>{try{const p={id:req.body.id||`P-${Date.now()}`,sku:req.body.sku,name:req.body.name,category:req.body.category||'Other',price:Number(req.body.price||0),stock:Number(req.body.stock||0),reorder:Number(req.body.reorder||0),active:req.body.active!==false};if(!p.sku||!p.name)return res.status(400).json({error:'SKU and product name required'});if(useDb){const r=await q('insert into products(id,sku,name,category,price,stock,reorder,active) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[p.id,p.sku,p.name,p.category,p.price,p.stock,p.reorder,p.active]);audit('CREATE','PRODUCT',p.id,req.user,p);return res.status(201).json(r.rows[0])}const d=load();d.products.push(p);save(d);audit('CREATE','PRODUCT',p.id,req.user,p);res.status(201).json(p)}catch(e){res.status(500).json({error:e.message})}});
app.patch('/api/products/:id',auth,role('ADMIN','MANAGER'),async(req,res)=>{try{if(useDb){const fields=['name','category','price','stock','reorder','active'];const sets=[];const vals=[];fields.forEach(f=>{if(req.body[f]!==undefined){sets.push(`${f}=$${vals.length+1}`);vals.push(req.body[f])}});if(!sets.length)return res.status(400).json({error:'No changes'});vals.push(req.params.id);const r=await q(`update products set ${sets.join(',')} where id=$${vals.length} returning *`,vals);if(!r.rows[0])return res.status(404).json({error:'Product not found'});audit('UPDATE','PRODUCT',req.params.id,req.user,req.body);return res.json(r.rows[0])}const d=load(),p=d.products.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Product not found'});Object.assign(p,req.body);save(d);audit('UPDATE','PRODUCT',p.id,req.user,req.body);res.json(p)}catch(e){res.status(500).json({error:e.message})}});

// Customers / drivers
app.post('/api/customers',auth,async(req,res)=>{try{const c={id:req.body.id||`CUS-${Date.now()}`,name:req.body.name,phone:req.body.phone||'',email:req.body.email||'',type:req.body.type||'Retail',notes:req.body.notes||''};if(!c.name)return res.status(400).json({error:'Customer name required'});if(useDb){const r=await q('insert into customers(id,name,phone,email,type,notes) values($1,$2,$3,$4,$5,$6) returning *',[c.id,c.name,c.phone,c.email,c.type,c.notes]);return res.status(201).json(r.rows[0])}const d=load();d.customers.push(c);save(d);res.status(201).json(c)}catch(e){res.status(500).json({error:e.message})}});

// POS sales + payments
app.post('/api/sales',auth,async(req,res)=>{try{const b=req.body||{},sale={id:b.id||saleId(),customer:b.customer||'Walk-in Customer',items:b.items||[],method:b.method||'Cash',amount:Number(b.amount||0),status:b.status||'Paid',ticketId:b.ticketId||null,cashier:req.user.name,createdAt:new Date().toISOString()};if(useDb){const client=await pool.connect();try{await client.query('begin');const r=await client.query('insert into sales(id,customer,items,method,amount,status,ticket_id,cashier) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[sale.id,sale.customer,JSON.stringify(sale.items),sale.method,sale.amount,sale.status,sale.ticketId,sale.cashier]);for(const item of sale.items){if(item.stockManaged){await client.query('update products set stock=greatest(0,stock-$1) where id=$2',[Number(item.qty||1),item.id])}}await client.query('commit');audit('CREATE','SALE',sale.id,req.user,sale);return res.status(201).json(r.rows[0])}catch(e){await client.query('rollback');throw e}finally{client.release()}}const d=load();d.sales.push(sale);d.posTransactions=d.posTransactions||[];d.posTransactions.push({time:new Date().toLocaleTimeString(),customer:sale.customer,item:sale.items.map(x=>`${x.name} x${x.qty||1}`).join(', '),method:sale.method,amount:sale.amount,status:sale.status});for(const item of sale.items){const p=d.products.find(x=>x.id===item.id);if(p&&item.stockManaged)p.stock=Math.max(0,p.stock-Number(item.qty||1))}save(d);audit('CREATE','SALE',sale.id,req.user,sale);res.status(201).json(sale)}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/payments',auth,async(req,res)=>{try{const p={ref:req.body.ref||`PAY-${Date.now()}`,method:req.body.method||'Cash',amount:Number(req.body.amount||0),status:req.body.status||'Success',phone:req.body.phone||'',saleId:req.body.saleId||null,createdAt:new Date().toISOString()};if(useDb){const r=await q('insert into payments(ref,method,amount,status,phone,sale_id) values($1,$2,$3,$4,$5,$6) returning *',[p.ref,p.method,p.amount,p.status,p.phone,p.saleId]);audit('CREATE','PAYMENT',p.ref,req.user,p);return res.status(201).json(r.rows[0])}const d=load();d.payments.push(p);save(d);audit('CREATE','PAYMENT',p.ref,req.user,p);res.status(201).json(p)}catch(e){res.status(500).json({error:e.message})}});

// Ticketing
app.get('/api/tickets',auth,async(req,res)=>{try{if(useDb){const r=await q('select * from tickets order by issued_at desc');return res.json(r.rows.map(t=>({...t,status:expiryStatus(t)})))}const d=load();d.tickets.forEach(t=>{const s=expiryStatus(t);if(s!==t.status)t.status=s});save(d);res.json(d.tickets)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/tickets',auth,async(req,res)=>{try{const b=req.body||{},t={id:b.id||ticketId(),customer:b.customer||'Walk-in Customer',phone:b.phone||'',type:b.type||'Service',service:b.service||'Service',amount:Number(b.amount||0),method:b.method||'Cash',station:b.station||'Any Station',expiry:b.expiry||new Date(Date.now()+86400000).toISOString(),status:'ACTIVE',createdBy:req.user.name,issuedAt:new Date().toISOString()};if(useDb){const r=await q('insert into tickets(id,customer,phone,type,service,amount,method,station,expiry,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *',[t.id,t.customer,t.phone,t.type,t.service,t.amount,t.method,t.station,t.expiry,t.status,t.createdBy]);audit('CREATE','TICKET',t.id,req.user,t);return res.status(201).json(r.rows[0])}const d=load();d.tickets.push(t);save(d);audit('CREATE','TICKET',t.id,req.user,t);res.status(201).json(t)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/tickets/:id',auth,async(req,res)=>{try{if(useDb){const r=await q('select * from tickets where lower(id)=lower($1)',[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Ticket not found'});return res.json(r.rows[0])}const t=load().tickets.find(x=>x.id.toLowerCase()===req.params.id.toLowerCase());res.status(t?200:404).json(t||{error:'Ticket not found'})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/tickets/:id/use',auth,async(req,res)=>{try{if(useDb){const r=await q("update tickets set status='USED',used_at=now(),used_by=$2 where lower(id)=lower($1) and status='ACTIVE' and expiry>now() returning *",[req.params.id,req.user.name]);if(!r.rows[0])return res.status(409).json({error:'Ticket is not active, valid or already used'});audit('USE','TICKET',req.params.id,req.user);return res.json(r.rows[0])}const d=load(),t=d.tickets.find(x=>x.id.toLowerCase()===req.params.id.toLowerCase());if(!t)return res.status(404).json({error:'Ticket not found'});if(expiryStatus(t)!=='ACTIVE')return res.status(409).json({error:`Ticket is ${expiryStatus(t)}`});t.status='USED';t.usedAt=new Date().toISOString();t.usedBy=req.user.name;save(d);audit('USE','TICKET',t.id,req.user);res.json(t)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/tickets/:id/qr',auth,async(req,res)=>{try{const svg=await QRCode.toString(req.params.id,{type:'svg',margin:1,width:240});res.type('svg').send(svg)}catch(e){res.status(500).json({error:e.message})}});

// Battery swap authorization: validates ticket, station and battery before completing.
app.post('/api/swaps',auth,async(req,res)=>{try{const b=req.body||{};if(!b.ticketId||!b.driverId||!b.stationId||!b.newBatteryId)return res.status(400).json({error:'ticketId, driverId, stationId and newBatteryId are required'});let ticket,driver,station,battery;if(useDb){const [tr,dr,sr,br]=await Promise.all([q('select * from tickets where lower(id)=lower($1)',[b.ticketId]),q('select * from drivers where id=$1',[b.driverId]),q('select * from stations where id=$1',[b.stationId]),q('select * from batteries where id=$1',[b.newBatteryId])]);ticket=tr.rows[0];driver=dr.rows[0];station=sr.rows[0];battery=br.rows[0]}else{const d=load();ticket=d.tickets.find(x=>x.id.toLowerCase()===b.ticketId.toLowerCase());driver=d.drivers.find(x=>x.id===b.driverId);station=d.stations.find(x=>x.id===b.stationId);battery=d.batteries.find(x=>x.id===b.newBatteryId)}if(!ticket||!driver||!station||!battery)return res.status(404).json({error:'Ticket, driver, station or battery not found'});if(expiryStatus(ticket)!=='ACTIVE')return res.status(409).json({error:`Ticket is ${expiryStatus(ticket)}`});if(station.online===false)return res.status(409).json({error:'Station is offline'});if(battery.status!=='Available'||Number(battery.soc)<50)return res.status(409).json({error:'Battery is not available for swap'});const swap={id:`SWAP-${Date.now()}`,ticketId:b.ticketId,driverId:b.driverId,stationId:b.stationId,newBatteryId:b.newBatteryId,oldBatteryId:b.oldBatteryId||'',amount:Number(b.amount||ticket.amount||0),status:'COMPLETED',createdAt:new Date().toISOString()};if(useDb){const client=await pool.connect();try{await client.query('begin');await client.query("update tickets set status='USED',used_at=now(),used_by=$2 where lower(id)=lower($1)",[b.ticketId,req.user.name]);await client.query("update batteries set status='In Use',updated_at=now() where id=$1",[b.newBatteryId]);await client.query('insert into swaps(id,ticket_id,driver_id,station_id,old_battery_id,new_battery_id,amount,status) values($1,$2,$3,$4,$5,$6,$7,$8)',[swap.id,swap.ticketId,swap.driverId,swap.stationId,swap.oldBatteryId,swap.newBatteryId,swap.amount,swap.status]);await client.query('commit');}catch(e){await client.query('rollback');throw e}finally{client.release()}}else{const d=load();const t=d.tickets.find(x=>x.id===b.ticketId);t.status='USED';t.usedAt=swap.createdAt;const bb=d.batteries.find(x=>x.id===b.newBatteryId);bb.status='In Use';d.swaps.push({...swap,driver:driver.name,station:station.name,new:b.newBatteryId,old:b.oldBatteryId||''});save(d)}audit('COMPLETE','SWAP',swap.id,req.user,swap);res.status(201).json(swap)}catch(e){res.status(500).json({error:e.message})}});

// Cashier shifts
app.post('/api/shifts/open',auth,async(req,res)=>{try{const shift={id:`SHIFT-${Date.now()}`,cashier:req.user.name,cashierId:req.user.id,openedAt:new Date().toISOString(),openingCash:Number(req.body.openingCash||0),status:'OPEN'};if(useDb){const r=await q("insert into shifts(id,cashier,cashier_id,opened_at,opening_cash,status) values($1,$2,$3,$4,$5,'OPEN') returning *",[shift.id,shift.cashier,shift.cashierId,shift.openedAt,shift.openingCash]);return res.status(201).json(r.rows[0])}const d=load();d.shifts.push(shift);save(d);res.status(201).json(shift)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/shifts/:id/close',auth,async(req,res)=>{try{const closingCash=Number(req.body.closingCash||0);if(useDb){const r=await q("update shifts set closed_at=now(),closing_cash=$2,status='CLOSED' where id=$1 and status='OPEN' returning *",[req.params.id,closingCash]);if(!r.rows[0])return res.status(404).json({error:'Open shift not found'});return res.json(r.rows[0])}const d=load(),s=d.shifts.find(x=>x.id===req.params.id&&x.status==='OPEN');if(!s)return res.status(404).json({error:'Open shift not found'});s.closedAt=new Date().toISOString();s.closingCash=closingCash;s.status='CLOSED';save(d);res.json(s)}catch(e){res.status(500).json({error:e.message})}});

// Expenses
app.post('/api/expenses',auth,role('ADMIN','MANAGER'),async(req,res)=>{try{const e={id:`EXP-${Date.now()}`,category:req.body.category||'General',description:req.body.description||'',amount:Number(req.body.amount||0),paymentMethod:req.body.paymentMethod||'Cash',spentAt:new Date().toISOString(),createdBy:req.user.name};if(!e.amount)return res.status(400).json({error:'Expense amount required'});if(useDb){const r=await q('insert into expenses(id,category,description,amount,payment_method,spent_at,created_by) values($1,$2,$3,$4,$5,$6,$7) returning *',[e.id,e.category,e.description,e.amount,e.paymentMethod,e.spentAt,e.createdBy]);audit('CREATE','EXPENSE',e.id,req.user,e);return res.status(201).json(r.rows[0])}const d=load();d.expenses.push(e);save(d);audit('CREATE','EXPENSE',e.id,req.user,e);res.status(201).json(e)}catch(err){res.status(500).json({error:err.message})}});

// M-Pesa STK Push + callback. Credentials stay server-side in .env.
async function mpesaToken(){const key=process.env.MPESA_CONSUMER_KEY,secret=process.env.MPESA_CONSUMER_SECRET;if(!key||!secret)throw new Error('M-Pesa credentials are not configured');const base=process.env.MPESA_ENV==='production'?'https://api.safaricom.co.ke':'https://sandbox.safaricom.co.ke';const auth=Buffer.from(`${key}:${secret}`).toString('base64');const r=await fetch(`${base}/oauth/v1/generate?grant_type=client_credentials`,{headers:{Authorization:`Basic ${auth}`}});if(!r.ok)throw new Error(`M-Pesa OAuth failed (${r.status})`);return (await r.json()).access_token}
app.post('/api/payments/mpesa/stkpush',auth,async(req,res)=>{try{const phone=String(req.body.phone||'').replace(/\D/g,'');const amount=Math.round(Number(req.body.amount||0));if(!/^254\d{9}$/.test(phone)||amount<=0)return res.status(400).json({error:'Use phone format 2547XXXXXXXX and a positive amount'});const shortCode=process.env.MPESA_SHORTCODE,passkey=process.env.MPESA_PASSKEY;if(!shortCode||!passkey)return res.status(503).json({error:'M-Pesa shortcode/passkey not configured'});const timestamp=new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);const password=Buffer.from(`${shortCode}${passkey}${timestamp}`).toString('base64');const base=process.env.MPESA_ENV==='production'?'https://api.safaricom.co.ke':'https://sandbox.safaricom.co.ke';const token=await mpesaToken();const body={BusinessShortCode:shortCode,Password:password,Timestamp:timestamp,TransactionType:process.env.MPESA_TRANSACTION_TYPE||'CustomerPayBillOnline',Amount:amount,PartyA:phone,PartyB:shortCode,PhoneNumber:phone,CallBackURL:process.env.MPESA_CALLBACK_URL,AccountReference:String(req.body.reference||'SPIRO-KAREN').slice(0,12),TransactionDesc:String(req.body.description||'Spiro Karen payment').slice(0,20)};const r=await fetch(`${base}/mpesa/stkpush/v1/processrequest`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();res.status(r.ok?200:502).json(j)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/payments/mpesa/callback',(req,res)=>{try{const cb=req.body?.Body?.stkCallback||{};const d=load();d.payments.push({ref:cb.CheckoutRequestID||`MPESA-${Date.now()}`,method:'M-Pesa',amount:Number(cb.CallbackMetadata?.Item?.find(x=>x.Name==='Amount')?.Value||0),status:Number(cb.ResultCode)===0?'Success':'Failed',phone:cb.CallbackMetadata?.Item?.find(x=>x.Name==='PhoneNumber')?.Value||'',mpesaReceipt:cb.CallbackMetadata?.Item?.find(x=>x.Name==='MpesaReceiptNumber')?.Value||'',createdAt:new Date().toISOString(),raw:req.body});save(d);res.json({ResultCode:0,ResultDesc:'Accepted'})}catch(e){res.json({ResultCode:0,ResultDesc:'Accepted'})}});

app.get('/api/config',(req,res)=>res.json({company:'Spiro Karen',currency:'KES',version:'3.0.0',paymentProviders:{mpesa:!!(process.env.MPESA_CONSUMER_KEY&&process.env.MPESA_CONSUMER_SECRET),stripe:!!process.env.STRIPE_SECRET_KEY},features:{ticketing:true,swaps:true,inventory:true,shifts:true,expenses:true,mpesa:true}}));

app.use(express.static(PUBLIC));
app.get('*',(req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));
ensureDb().then(()=>app.listen(PORT,()=>console.log(`Spiro Karen Business System: http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
